version: 2

project_name: vget

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/vget
    binary: vget
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/guiyumin/vget/internal/version.Version={{.Version}}
      - -X github.com/guiyumin/vget/internal/version.Commit={{.Commit}}
      - -X github.com/guiyumin/vget/internal/version.Date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows: only amd64 supported
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: guiyumin
    name: vget
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
